package io.hirasawa.server.osuapi

import java.time.Instant

data class OsuApiBeatmap(
    val beatmapsetId: Int,
    val beatmapId: Int,
    val approved: Int,
    val totalLength: Int,
    val hitLength: Int,
    val version: String,
    val fileMd5: String,
    val diffSize: Float,
    val diffOverall: Float,
    val diffApproach: Float,
    val diffDrain: Float,
    val mode: Int,
    val countNormal: Int,
    val countSlider: Int,
    val countSpinner: Int,
    val submitDate: String,
    val approvedDate: String,
    val lastUpdate: String,
    val artist: String,
    val artistUnicode: String,
    val creator: String,
    val creatorId: Int,
    val bpm: Float,
    val source: String,
    val genreId: Int,
    val languageId: Int,
    val title: String,
    val favouriteCount: Int,
    val rating: Float,
    val storyboard: Boolean,
    val video: Boolean,
    val downloadUnavailable: Boolean,
    val audioUnavailable: Boolean,
    val playcount: Int,
    val passcount: Int,
    val packs: String,
    val maxCombo: Int,
    val diffAim: Float,
    val diffSpeed: Float,
    val difficultyrating: Float
)