# This workflow will test a JVM project with Gradle
# Based on Gradle building example from Github

name: Publish build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: gradle-report
        path: build/reports/tests/test/
    - name: Build with Gradle
      run: ./gradlew build
    - name: Set version environment variable
      run: echo "VERSION_NAME=$(echo ${{ github.ref }} | cut -c 2-)" >> $GITHUB_ENV
    - name: Create draft release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Upload application
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/HirasawaBancho-${{ env.VERSION_NAME }}.jar
        asset_name: HirasawaBancho-${{ env.VERSION_NAME }}.jar
        asset_content_type: application/java-archive
    - name: Upload API
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/HirasawaBancho-${{ env.VERSION_NAME }}-api.jar
        asset_name: HirasawaBancho-${{ env.VERSION_NAME }}-api.jar
        asset_content_type: application/java-archive
    - name: Upload Javadoc
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/HirasawaBancho-${{ env.VERSION_NAME }}-javadoc.jar
        asset_name: HirasawaBancho-${{ env.VERSION_NAME }}-javadoc.jar
        asset_content_type: application/java-archive
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}